### ISSUE TITLE
Enable /tp command for spectator team

### ISSUE THREAD

**Issue by Mew2K** [Warzone/mars#5]
In TGM, players on the spectator team were previously able to /tp to players. Thus, this feature should be imported over to the Mars project.

**Comment by ishman123** [comment]
Also add
> Users can also click on names to teleport to players "While in the spectator team ofc" The feature already has a hover over tag or whatever you wanna call it all it needs is permissions

**Comment by BennyDoesStuff** [comment]
did #7 resolve this issue?

**Comment by TBG1000** [comment]
> did #7 resolve this issue?

It did. It's live since a couple of minutes ago.

> Also add
> 
> > Users can also click on names to teleport to players "While in the spectator team ofc" The feature already has a hover over tag or whatever you wanna call it all it needs is permissions

Also supported now for observers
